workflows:
  hello-world:
    name: Native Android
    scripts:
        - name: Test
          script: |
                set -e
                ./gradlew connectedAndroidTest
                adb logcat -d > emulator.log
          test_report: app/build/outputs/androidTest-results/connected/*.xml
